from __future__ import annotations

from typing import Any


def obstacle_templates() -> dict[str, list[dict[str, Any]]]:
    return {
        "starter": [
            {
                "type": "rect",
                "x": 280,
                "y": 980,
                "width": 300,
                "height": 30,
                "angle_deg": -22,
                "fill_color": "#182037",
            },
            {
                "type": "moving_rect",
                "x": 760,
                "y": 1120,
                "width": 290,
                "height": 30,
                "angle_deg": 18,
                "amplitude": 120,
                "frequency_hz": 0.24,
                "axis": "x",
                "fill_color": "#182037",
            },
            {
                "type": "ring_gap",
                "x": 540,
                "y": 1380,
                "radius": 160,
                "thickness": 32,
                "rotation_speed_deg": 90,
                "gap_center_deg": 270,
                "gap_size_deg": 64,
                "fill_color": "#182037",
            },
            {
                "type": "spinner",
                "x": 540,
                "y": 1680,
                "length": 340,
                "thickness": 24,
                "spin_speed_deg": 160,
                "fill_color": "#182037",
            },
            {
                "type": "one_way_gate",
                "x": 540,
                "y": 1940,
                "width": 620,
                "height": 24,
                "one_way": "down",
                "fill_color": "#182037",
            },
        ],
        "rings": [
            {
                "type": "ring_gap",
                "x": 350,
                "y": 980,
                "radius": 126,
                "thickness": 32,
                "gap_center_deg": 250,
                "gap_size_deg": 62,
                "fill_color": "#182037",
            },
            {
                "type": "ring_gap",
                "x": 730,
                "y": 1210,
                "radius": 130,
                "thickness": 32,
                "gap_center_deg": 200,
                "gap_size_deg": 58,
                "fill_color": "#182037",
            },
            {
                "type": "ring_gap",
                "x": 420,
                "y": 1460,
                "radius": 142,
                "thickness": 32,
                "gap_center_deg": 280,
                "gap_size_deg": 60,
                "fill_color": "#182037",
            },
            {
                "type": "ring_gap",
                "x": 700,
                "y": 1730,
                "radius": 132,
                "thickness": 32,
                "gap_center_deg": 245,
                "gap_size_deg": 58,
                "fill_color": "#182037",
            },
            {
                "type": "spinner",
                "x": 540,
                "y": 2060,
                "length": 320,
                "thickness": 24,
                "spin_speed_deg": 150,
                "fill_color": "#182037",
            },
        ],
        "gates": [
            {
                "type": "rect",
                "x": 260,
                "y": 940,
                "width": 320,
                "height": 30,
                "angle_deg": -18,
                "fill_color": "#182037",
            },
            {
                "type": "one_way_gate",
                "x": 540,
                "y": 1120,
                "width": 640,
                "height": 24,
                "one_way": "down",
                "fill_color": "#182037",
            },
            {
                "type": "one_way_gate",
                "x": 540,
                "y": 1270,
                "width": 640,
                "height": 24,
                "one_way": "up",
                "fill_color": "#182037",
            },
            {
                "type": "moving_rect",
                "x": 740,
                "y": 1510,
                "width": 320,
                "height": 30,
                "angle_deg": 14,
                "axis": "x",
                "amplitude": 100,
                "frequency_hz": 0.24,
                "fill_color": "#182037",
            },
            {
                "type": "pendulum",
                "x": 540,
                "y": 1820,
                "pivot_x": 540,
                "pivot_y": 1820,
                "length": 290,
                "angle_deg": 15,
                "amplitude": 56,
                "frequency_hz": 0.45,
                "thickness": 18,
                "fill_color": "#182037",
            },
        ],
    }
